# Generated by Django 6.0.8 on 2026-09-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_options_remove_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
