# Generated by Django 6.1 on 2026-08-11 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название курса', max_length=200, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='courses/previews/', verbose_name='Превью (картинка)')),
                ('description', models.TextField(help_text='Введите описание курса', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название урока', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание урока', verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lessons/previews/', verbose_name='Превью (картинка)')),
                ('video_url', models.URLField(help_text='Введите ссылку на видео', verbose_name='Ссылка на видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['created_at'],
            },
        ),
    ]
